package ru.maxmorev.eshop.commodity.api.entities;

public interface Constants {

    String ID_GENERATOR_COMMODITY = "ID_GENERATOR_COMMODITY";
    String ID_GENERATOR_COMMODITY_SEQUENCE_NAME = "RES_SEQUENCE_COMMODITY";

    String ID_GENERATOR_ATTRIBUTE = "ID_GENERATOR_ATTRIBUTE";
    String ID_GENERATOR_ATTRIBUTE_SEQUENCE_NAME = "RES_SEQUENCE_ATTRIBUTE";

    String ID_GENERATOR_ATTRIBUTE_VALUE = "ID_GENERATOR_ATTRIBUTE_VALUE";
    String ID_GENERATOR_ATTRIBUTE_VALUE_SEQUENCE_NAME = "RES_SEQUENCE_ATTRIBUTE_VALUE";

    String ID_GENERATOR_BRANCH = "ID_GENERATOR_BRANCH";
    String ID_GENERATOR_BRANCH_SEQUENCE_NAME = "RES_SEQUENCE_BRANCH";

    String ID_GENERATOR_BRANCH_ATTRIBUTE_SET = "ID_GENERATOR_ATTRIBUTE_SET";
    String ID_GENERATOR_BRANCH_ATTRIBUTE_SET_SEQUENCE_NAME = "RES_SEQUENCE_ATTRIBUTE_SET";

    String ID_GENERATOR_COMMODITY_TYPE = "ID_GENERATOR_COMMODITY_TYPE";
    String ID_GENERATOR_COMMODITY_TYPE_SEQUENCE_NAME = "RES_SEQUENCE_COMMODITY_TYPE";

}
